# Generated by Django 3.1 on 2022-03-08 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220304_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
