# Generated by Django 3.1 on 2022-04-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220328_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
